
import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author the1s
 */
public class Runner extends JPanel {

    /**
     * Creates new form Runner
     */
    public Runner() {
       //        try {
//            //URL = "https://www.google.com/";
//            URL url = new URL("https://www.google.com/");
//            URLConnection urlconnection = url.openConnection();
//            urlconnection.connect();
//        } catch (MalformedURLException ex) {
//            Logger.getLogger(Finder.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }
    
    @Override
    public void paint(Graphics g){
        
//        g.setColor(Color.BLACK);
//        g.drawRect(1300/3, 80, 390, 87 );
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
